apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
    - name: https
      port: 443